### ISSUE TITLE
Package requirements

### ISSUE THREAD

**Issue by DongxiaW** [AureliePeng/Keras-WaveletTransform#1]
Hello, 
I tried to implement your work. But the code has some bugs. I guess it could be the package version issue. It is appreciated if you could share the package version requirements. Thanks.

**Comment by AureliePeng** [comment]
Hello !
I made this code before Keras was integrated to Tensorflow so as you said it's extremely likely that there are package version issues now. Changing all the keras.xxx imports to tf.keras.xxx would solve some of the issues ?
Unfortunately I didn't keep a proper requirement list back then so I'm unable to give you exact Keras version I used :(

**Comment by DongxiaW** [comment]
> Hello !
> I made this code before Keras was integrated to Tensorflow so as you said it's extremely likely that there are package version issues now. Maybe changing all the keras.xxx imports to tf.keras.xxx would solve some of the issues ?
> Unfortunately I didn't keep a proper requirement list back then so I'm unable to give you exact Keras version I used :(

I see. Thanks for the advice. I changed to the Tensorflow package and use the same DIV2K_train_HR dataset for test. But I still got a TypeError showing like this: 
Any hint to solve it? Thanks!

Epoch 1/400
Traceback (most recent call last):
  File "init.py", line 50, in <module>
    train(FLAGS)
  File "/Users/wudongxia/Desktop/Keras-WaveletTransform-master/train.py", line 66, in train
    validation_data=valid_generator
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1829, in fit_generator
    initial_epoch=initial_epoch)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    /Users/wudongxia/Desktop/Keras-WaveletTransform-master/utils.py:74 psnr  *
        if mse == 0:
    /anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/operators/control_flow.py:951 if_stmt
        _tf_if_stmt(cond, body, orelse, get_state, set_state, symbol_names, nouts)
    /anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/operators/control_flow.py:996 _tf_if_stmt
        cond, aug_body, aug_orelse, strict=True)
    /anaconda3/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:507 new_func
        return func(*args, **kwargs)
    /anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:1180 cond
        return cond_v2.cond_v2(pred, true_fn, false_fn, name)
    /anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/cond_v2.py:92 cond_v2
        op_return_value=pred)
    /anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py:986 func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    /anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/operators/control_flow.py:992 aug_orelse
        _verify_tf_cond_vars(new_body_vars_[0], new_orelse_vars, symbol_names)
    /anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/operators/control_flow.py:288 _verify_tf_cond_vars
        functools.partial(verify_single_cond_var, name), body_var, orelse_var)
    /anaconda3/lib/python3.7/site-packages/tensorflow/python/util/nest.py:635 map_structure
        structure[0], [func(*x) for x in entries],
    /anaconda3/lib/python3.7/site-packages/tensorflow/python/util/nest.py:635 <listcomp>
        structure[0], [func(*x) for x in entries],
    /anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/operators/control_flow.py:260 verify_single_cond_var
        orelse_var.dtype.name))

    TypeError: 'retval_' has dtype int32 in the main branch, but dtype float32 in the else branch
